version: 2
jobs:

  install_and_validate:
    docker:
      - image: 18fgsa/devsecops-builder:alpine
    steps:
      - checkout

      - run:
          name: Validate Packer templates
          command: /usr/bin/make validate_packer

      - run:
          name: Download Ansible dependencies
          command: /usr/bin/make roles
      - run:
          name: Validate Ansible playbooks
          command: /usr/bin/make validate_ansible
      - persist_to_workspace:
          root: .
          paths:
            - ./*

  deploy_rhel7:
    docker:
      - image: 18fgsa/devsecops-builder:alpine
    steps:
      - attach_workspace:
          at: .

      - add_ssh_keys
      - run:
          name: Disable host key checking
          command: printf "\nHost *\n\tStrictHostKeyChecking no" >> ~/.ssh/config

      - run:
          name: Build rhel7 AMI
          command: |
            export USER=$(whoami)
            make rhel7

workflows:
  version: 2

  validate_and_deploy:
    jobs:
      - install_and_validate
      - deploy_rhel7: &deploy
          filters:
            branches:
              only:
                - master
          requires:
            - install_and_validate
