version: 2
jobs:

  install_and_validate:
    docker:
      - image: 18fgsa/devsecops-builder:alpine
    steps:
      - checkout

      - run:
          name: Validate Packer templates
          command: /usr/bin/make validate_packer

      - run:
          name: Download Ansible dependencies
          command: /usr/bin/make roles
      - run:
          name: Validate Ansible playbooks
          command: /usr/bin/make validate_ansible
      - persist_to_workspace:
          root: .
          paths:
            - ./*

  deploy_rhel7:
    docker:
      - image: 18fgsa/devsecops-builder:alpine
    steps:
      - attach_workspace:
          at: .

      - add_ssh_keys
      - run:
          name: Disable host key checking
          command: printf "\nHost *\n\tStrictHostKeyChecking no" >> ~/.ssh/config

      # - run:
      #     name: Get Tenants Info, store in environment variable
      #     command: |
      #       echo "export TENANT_ACCOUNTS=$(aws s3 cp --quiet s3://grace-tenant-info/tenant-info/tenants.txt /dev/stdout)" >> $BASH_ENV
      #       source $BASH_ENV

      - run:
          name: Build rhel7 AMI
          command: |
            export TENANT_ACCOUNTS=$(aws s3 cp --quiet s3://grace-tenant-info/tenant-info/tenants.txt /dev/stdout)
            export USER=$(whoami)
            make rhel7
          no_output_timeout: 1h

workflows:
  version: 2

  weekly:
    triggers:
      - schedule:
          cron: "0 3 * * 6"
          filters:
            branches:
              only:
                - master
    jobs:
      - install_and_validate
      - deploy_rhel7:
          filters:
            branches:
              only:
                - master
          requires:
            - install_and_validate

  validate_and_deploy:
    jobs:
      - install_and_validate
      - deploy_rhel7:
          filters:
            branches:
              only:
                - master
                - tenant-accounts-testing
          requires:
            - install_and_validate
